/**
 * Currencies
 */
export const FETCH_CURRENCIES_REQUESTED = 'FETCH_CURRENCIES_REQUESTED';
export const FETCH_CURRENCIES_SUCCEEDED = 'FETCH_CURRENCIES_SUCCEEDED';
export const FETCH_CURRENCIES_FAILED = 'FETCH_CURRENCIES_FAILED';

export const FETCH_CURRENCY_RATES_REQUESTED = 'FETCH_CURRENCY_RATES_REQUESTED';
export const FETCH_CURRENCY_RATES_SUCCEEDED = 'FETCH_CURRENCY_RATES_SUCCEEDED';
export const FETCH_CURRENCY_RATES_FAILED = 'FETCH_CURRENCY_RATES_FAILED';

export const TOGGLE_CURRENCY = 'TOGGLE_CURRENCY';

export const FILTER_CURRENCIES = 'FILTER_CURRENCIES';
export const FILTER_CURRENCIES_REQUESTED = 'FILTER_CURRENCIES_REQUESTED';


/**
 * Page
 */
export const SET_PAGE_TITLE = 'SET_PAGE_TITLE';


/**
 * Loading
 */
export const ADD_LOADING = 'ADD_LOADING';
export const REMOVE_LOADING = 'REMOVE_LOADING';
